imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @ZenwebAventureParcBundle/Resources/config/admin.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ DpCalendarBundle, ZenwebAventureParcBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#Friends Of Symfony
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Zenweb\Aventure\ParcBundle\Entity\User
    group:
        group_class: Zenweb\Aventure\ParcBundle\Entity\Group

sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.calendar: ~

sonata_admin:
    title: Aventure Administration
    templates:
        layout: ZenwebAventureParcBundle:Admin:standard_layout.html.twig
        edit:   ZenwebAventureParcBundle:CRUD:base_edit.html.twig
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }
            - { position: right, type: sonata.block.service.calendar}

sonata_user:
    security_acl: true
    manager_type: orm # can be orm or mongodb
    class:                  # Entity Classes
        user:               Zenweb\Aventure\ParcBundle\Entity\User
        group:              Zenweb\Aventure\ParcBundle\Entity\Group

genemu_form:
    date: ~

parameters:
    sonata.user.admin.user.class: Zenweb\Aventure\ParcBundle\Admin\Model\UserAdmin