zenweb_aventure_parc:
    resource: "@ZenwebAventureParcBundle/Resources/config/routing.yml"
    prefix:   /

#zenweb_aventure_user:
#    resource: "@ZenwebAventureUserBundle/Resources/config/routing.yml"
#    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

#sonata_user_impersonating:
#    pattern: /
#    defaults: { _controller: SonataPageBundle:Page:catchAll }

dp_calendar:
    resource: "@DpCalendarBundle/Resources/config/routing.yml"
    prefix:

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register