zenweb_aventure_parc:
    resource: "@ZenwebAventureParcBundle/Resources/config/routing.yml"
    prefix:   /

zenweb_aventure_parc_payment:
    resource: "@ZenwebAventureParcPaymentBundle/Resources/config/routing.yml"
    prefix:   /

zenweb_aventure_user:
    resource: "@ZenwebAventureUserBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

#sonata_user_impersonating:
#    pattern: /
#    defaults: { _controller: SonataPageBundle:Page:catchAll }

dp_calendar:
    resource: "@DpCalendarBundle/Resources/config/routing.yml"
    prefix:

sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile
