services:
    sonata.admin.parc:
        class: Zenweb\Aventure\ParcBundle\Admin\ParcAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Parcs", label: "Parcs" }
        arguments:
            - ~
            - Zenweb\Aventure\ParcBundle\Entity\Parc
            - ~
        calls:
            - [ setTranslationDomain, [ZenwebAventureParcBundle]]

    #sonata.admin.coupon:
    #    class: Zenweb\Aventure\ParcBundle\Admin\CouponAdmin
    #    tags:
    #        - { name: sonata.admin, manager_type: orm, group: "Promotions", label: "Coupon" }
    #    arguments:
    #        - ~
    #        - Zenweb\Aventure\ParcBundle\Entity\Coupon
    #        - ~
    #    calls:
    #        - [ setTranslationDomain, [ZenwebAventureParcBundle]]

    sonata.admin.typicalday:
        class: Zenweb\Aventure\ParcBundle\Admin\TypicalDayAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Parcs", label: "Journée type" }
        arguments:
            - ~
            - Zenweb\Aventure\ParcBundle\Entity\TypicalDay
            - ~
        calls:
            - [ setTranslationDomain, [ZenwebAventureParcBundle]]

    sonata.admin.activity:
        class: Zenweb\Aventure\ParcBundle\Admin\ActivityAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Parcs", label: "Activité" }
        arguments:
            - ~
            - Zenweb\Aventure\ParcBundle\Entity\Activity
            - ~
        calls:
            - [ setTranslationDomain, [ZenwebAventureParcBundle]]

    sonata.admin.timeslot:
        class: Zenweb\Aventure\ParcBundle\Admin\TimeSlotAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Parcs", label: "Créneau" }
        arguments:
            - ~
            - Zenweb\Aventure\ParcBundle\Entity\TimeSlot
            - ~
        calls:
            - [ setTranslationDomain, [ZenwebAventureParcBundle]]

    sonata.admin.extra:
        class: Zenweb\Aventure\ParcBundle\Admin\ExtraAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Parcs", label: "Options" }
        arguments:
            - ~
            - Zenweb\Aventure\ParcBundle\Entity\Extra
            - ~
        calls:
            - [ setTranslationDomain, [ZenwebAventureParcBundle]]

    sonata.admin.TierPrices:
        class: Zenweb\Aventure\ParcBundle\Admin\TierPriceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Parcs", label: "Prix", show_in_dashboard: false }
        arguments:
            - ~
            - Zenweb\Aventure\ParcBundle\Entity\TierPrice
            - ~
        calls:
            - [ setTranslationDomain, [ZenwebAventureParcBundle]]

    sonata.admin.price:
            class: Zenweb\Aventure\ParcBundle\Admin\PriceAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Parcs", label: "Prix" }
            arguments:
                - ~
                - Zenweb\Aventure\ParcBundle\Entity\Price
                - ~
            calls:
                - [ setTranslationDomain, [ZenwebAventureParcBundle]]

    sonata.admin.sales_flat_order:
        class: Zenweb\Aventure\ParcBundle\Admin\SalesFlatOrderAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Vente", label: "Commandes" }
        arguments:
            - ~
            - Zenweb\Aventure\ParcBundle\Entity\SalesFlatOrder
            - ~
        calls:
            - [ setTranslationDomain, [ZenwebAventureParcBundle]]

    sonata.admin.sales_flat_item:
        class: Zenweb\Aventure\ParcBundle\Admin\SalesFlatItemAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Vente", label: "Activités", show_in_dashboard: false }
        arguments:
            - ~
            - Zenweb\Aventure\ParcBundle\Entity\SalesFlatItem
            - ~
        calls:
            - [ setTranslationDomain, [ZenwebAventureParcBundle]]

    sonata.block.service.calendar:
        class: Zenweb\Aventure\ParcBundle\Block\AdminCalendarBlockService
        arguments: [ "sonata.block.service.calendar", @templating ]
        tags:
            - { name: sonata.block }

    sonata.block.service.recent_orders:
        class: Zenweb\Aventure\ParcBundle\Block\RecentOrdersBlockService
        arguments: [ "sonata.block.service.recent_orders", @templating, @security.context, @zenweb_aventure_parc.order.manager ]
        tags:
            - { name: sonata.block }