#zenweb_aventure_parc_homepage:
#    pattern:  /hello/{name}
#    defaults: { _controller: ZenwebAventureParcBundle:Default:index }
zenweb_aventure_parc_calendar_ajax_admin:
    pattern:  /admin/calendar/ajax_admin
    defaults: { _controller: ZenwebAventureParcBundle:Calendar:ajaxAdmin }
zenweb_aventure_parc_calendar_admin_load:
    pattern:  /admin/calendar/load
    defaults: { _controller: ZenwebAventureParcBundle:Calendar:load }