#zenweb_aventure_parc_homepage:
#    pattern:  /hello/{name}
#    defaults: { _controller: ZenwebAventureParcBundle:Default:index }
zenweb_aventure_parc_calendar_ajax_admin:
    pattern:  /admin/calendar/ajax_admin
    defaults: { _controller: ZenwebAventureParcBundle:Calendar:ajaxAdmin }
zenweb_aventure_parc_calendar_admin_load:
    pattern:  /admin/calendar/load
    defaults: { _controller: ZenwebAventureParcBundle:Calendar:load }
zenweb_aventure_parc_order_create_form:
    pattern:  /admin/order/create
    defaults: { _controller: ZenwebAventureParcBundle:Admin/Order:createOrder }
zenweb_aventure_parc_orders:
    pattern:  /admin/order
    defaults: { _controller: ZenwebAventureParcBundle:Admin/Order:list }
zenweb_aventure_parc_admin_order_create_get_prices:
    pattern:  /admin/order/get_prices
    defaults: { _controller: ZenwebAventureParcBundle:Admin/Order:getPrices }


zenweb_aventure_parc_fo_home:
    pattern: /
    defaults: { _controller: ZenwebAventureParcBundle:Front:home }
zenweb_aventure_parc_fo_contact:
    pattern: /contact
    defaults: { _controller: ZenwebAventureParcBundle:Front:contact }
zenweb_aventure_parc_fo_mentions:
    pattern: /mentions-legales
    defaults: { _controller: ZenwebAventureParcBundle:Front:mentions }
zenweb_aventure_parc_fo_construction:
    pattern: /construction
    defaults: { _controller: ZenwebAventureParcBundle:Front:construction }
zenweb_aventure_parc_fo_faq:
    pattern: /questions-pratiques
    defaults: { _controller: ZenwebAventureParcBundle:Front:faq }

zenweb_aventure_parc_offres_gp:
    pattern: /vos-offres/grand-public
    defaults: { _controller: ZenwebAventureParcBundle:Offres:gp }
zenweb_aventure_parc_offres_groupe:
    pattern: /vos-offres/groupes-et-collectivites
    defaults: { _controller: ZenwebAventureParcBundle:Offres:groupe }
zenweb_aventure_parc_offres_scolaire:
    pattern: /vos-offres/scolaire-et-centres-de-loisirs
    defaults: { _controller: ZenwebAventureParcBundle:Offres:scolaire }
zenweb_aventure_parc_offres_seminaire:
    pattern: /vos-offres/seminaires-et-incentives-pro
    defaults: { _controller: ZenwebAventureParcBundle:Offres:seminaire }
