#zenweb_aventure_parc_homepage:
#    pattern:  /hello/{name}
#    defaults: { _controller: ZenwebAventureParcBundle:Default:index }
zenweb_aventure_parc_calendar_ajax_admin:
    pattern:  /admin/calendar/ajax_admin
    defaults: { _controller: ZenwebAventureParcBundle:Calendar:ajaxAdmin }
zenweb_aventure_parc_calendar_load:
    pattern:  /calendar/load
    defaults: { _controller: ZenwebAventureParcBundle:Calendar:load }
zenweb_aventure_parc_order_create_form:
    pattern:  /admin/order/create
    defaults: { _controller: ZenwebAventureParcBundle:Admin/Order:createOrder }
zenweb_aventure_parc_orders:
    pattern:  /admin/order
    defaults: { _controller: ZenwebAventureParcBundle:Admin/Order:list }
zenweb_aventure_parc_order_create_get_prices:
    pattern:  /order/get_prices
    defaults: { _controller: ZenwebAventureParcBundle:Front:getPrices }
zenweb_aventure_parc_order_create_get_prices_extra:
    pattern:  /order/get_prices_extra
    defaults: { _controller: ZenwebAventureParcBundle:Front:getPricesExtra }
zenweb_aventure_parc_order_create_get_ts:
    pattern:  /order/get_ts
    defaults: { _controller: ZenwebAventureParcBundle:Front:getTimeSlots }
zenweb_aventure_parc_admin_dashboard:
    pattern:  /admin/backoffice
    defaults: { _controller: ZenwebAventureParcBundle:Admin/Dashboard:list }
zenweb_aventure_parc_admin_dashboard_content:
    pattern:  /admin/backoffice/content/{parc}/{date}/{activity}
    defaults: { _controller: ZenwebAventureParcBundle:Admin/Dashboard:content, parc: null, date: null, activity: null }

zenweb_aventure_parc_fo_home:
    pattern: /
    defaults: { _controller: ZenwebAventureParcBundle:Front:home }
zenweb_aventure_parc_fo_show:
    pattern: /parc/{id}
    defaults: { _controller: ZenwebAventureParcBundle:Front:showParc }