parameters:
#    zenweb_aventure_parc.example.class: Zenweb\Aventure\ParcBundle\Example

services:
#    zenweb_aventure_parc.example:
#        class: %zenweb_aventure_parc.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    zenweb_aventure_parc.form.admin.flow.create.order:
        class: Zenweb\Aventure\ParcBundle\Form\Admin\CreateOrderFlow
        parent: craue.form.flow
        scope: request
        arguments: [ @doctrine.orm.entity_manager ]
    #zenweb_aventure_parc.user_creation:
    #    class: Zenweb\Aventure\ParcBundle\Form\EventListener\UserCreationListener
    #    arguments: [ @doctrine.orm.entity_manager ]