parameters:

services:
    zenweb_aventure_parc.form.admin.flow.create.order:
        class: Zenweb\Aventure\ParcBundle\Form\Admin\CreateOrderFlow
        parent: craue.form.flow
        scope: request
        arguments: [ @doctrine.orm.entity_manager ]

    zenweb_aventure_parc.form.checkout.flow.create.order:
        class: Zenweb\Aventure\ParcBundle\Form\Checkout\CreateOrderFlow
        parent: craue.form.flow
        scope: request
        arguments: [ @doctrine.orm.entity_manager, @security.context ]

    #zenweb_aventure_parc.user_creation:
    #    class: Zenweb\Aventure\ParcBundle\Form\EventListener\UserCreationListener
    #    arguments: [ @doctrine.orm.entity_manager ]
    zenweb_aventure_parc.order.manager:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - Zenweb\Aventure\ParcBundle\Entity\SalesFlatOrder

    zenweb_aventure_parc.order.form.status:
        class: Sonata\CoreBundle\Form\Type\StatusType
        arguments: [Zenweb\Aventure\ParcBundle\Entity\SalesFlatOrder, getStatusList, zenweb_order_status]
        tags:
            - { name: form.type, alias: zenweb_order_status }

    zenweb_aventure_parc.order.listener:
        class: Zenweb\Aventure\ParcBundle\Listener\OrderListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    zenweb_aventure_parc.timeslot.listener:
        class: Zenweb\Aventure\ParcBundle\Listener\TimeSlotListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    zenweb_aventure_parc.user.listener:
        class: Zenweb\Aventure\ParcBundle\Listener\UserListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    zenweb_aventure_parc.form.type.items:
        class: Zenweb\Aventure\ParcBundle\Form\SalesFlatItemType
        tags:
            - { name: form.type, alias: zenweb_aventure_parcbundle_salesflatitem }
        arguments: [ @doctrine.orm.entity_manager ]