parameters:
#    zenweb_aventure_parc.example.class: Zenweb\Aventure\ParcBundle\Example

services:
#    zenweb_aventure_parc.example:
#        class: %zenweb_aventure_parc.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
