Zenweb\Aventure\ParcBundle\Entity\Coupon:
    properties:
        name:
            - NotBlank: ~
Zenweb\Aventure\ParcBundle\Entity\Parc:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: name
            message: Le nom du parc est déjà utilisé pour un autre parc.
    properties:
        name:
            - NotBlank: ~
        mail:
            - Email:
                message: "{{ value }} n'est pas un email valide."
                checkMX: true
        fileImage:
            - File:
                maxSize: 8192k
        filePlan:
            - File:
                maxSize: 8192k
                mimeTypes: [application/pdf, application/x-pdf]
                mimeTypesMessage: Choisissez un fichier PDF valide

Zenweb\Aventure\ParcBundle\Entity\SalesFlatOrder:
    properties:
        bookingDate:
            - Date: ~
            - Zenweb\Aventure\ParcBundle\Validator\Constraints\DateRange:
                min: "today"
                groups: [flow_createOrder_step2, flow_createOrderFront_step3]
        items:
            - Count:
                min: 1
                minMessage: "Vous devez indiquer au moins une activité."
                groups: [flow_createOrderFront_step4]

Zenweb\Aventure\ParcBundle\Entity\SalesFlatItem:
    constraints:
        - Zenweb\Aventure\ParcBundle\Validator\Constraints\ActivityQuantity:
            groups: [flow_createOrderFront_step4]
    properties:
        qty:
            - NotBlank:
                message: "Veuillez remplir une quantité"
                groups: [flow_createOrderFront_step4]
            - Range:
                min: 1
                max: 50
                minMessage: "Veuillez saisir une quantité supérieure à 1."
                maxMessage: Vous ne devez pas dépasser 180cm
                groups: [flow_createOrderFront_step4]


Zenweb\Aventure\ParcBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: {fields: [email], groups: [flow_createOrderFront_step1], message:"Cet email est déjà utilisé."}
    properties:
        lastname:
            - NotBlank:
                message: "Veuillez remplir le champ Nom"
                groups: [flow_createOrderFront_step1]
            - Length:
                min: 2
                max: 64
                minMessage: "Votre nom doit faire au moins {{ limit }} caractères"
                maxMessage: "Votre nom ne peut pas être plus long que {{ limit }} caractères"
                groups: [flow_createOrderFront_step1]
        firstname:
            - NotBlank:
                message: "Veuillez remplir le champ Prénom"
                groups: [flow_createOrderFront_step1]
            - Length:
                min: 2
                max: 64
                minMessage: "Votre prénom doit faire au moins {{ limit }} caractères"
                maxMessage: "Votre prénom ne peut pas être plus long que {{ limit }} caractères"
                groups: [flow_createOrderFront_step1]
        email:
            - Email:
                message: "{{ value }} n'est pas un email valide."
                checkMX: true
                groups: [flow_createOrderFront_step1]
        plainPassword:
            - NotBlank:
                message: "Veuillez remplir le champ Mot de passe"
                groups: [flow_createOrderFront_step1]