parameters:
#    zenweb_accro_user.example.class: Zenweb\Accro\UserBundle\Example

services:
#    zenweb_accro_user.example:
#        class: %zenweb_accro_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
