<?php

namespace Zenweb\Aventure\ParcBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{
    public function getActivitiesByTypicalDay($idTypicalDay)
    {
        return $this->createQueryBuilder("p")
            ->innerJoin("ZenwebAventureParcBundle:TimeSlot", "ts", "WITH", "ts.activity = p.id")
            ->where("ts.id=:idTs and ts.enabled=:enabled")
            ->setParameter("idTs", $idTypicalDay)
            ->setParameter("enabled", true)
            ;
    }
}
