<?php

namespace Zenweb\Aventure\ParcBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExtraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtraRepository extends EntityRepository
{
    /**
     * @param $id
     *
     * @return int
     */

    public function getPrice($id)
    {
        /**
         * Subquery to get the min of each tier price.
         */
        $qb2 = $this->_em->createQueryBuilder();
        return $qb2->select('price')
            ->from('ZenwebAventureParcBundle:Extra', 'extra')
            ->where('extra.id=:id')
            ->setParameter("id", $id)
            ->getFirstResult();

    }
}
