<?php

namespace Zenweb\Aventure\ParcBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceRepository extends EntityRepository
{
    public function getPricesByTimeSlot($idTimeSlot)
    {
        return $this->createQueryBuilder("p")
            ->innerJoin("ZenwebAventureParcBundle:TimeSlot", "ts", "WITH", "ts.activity = p.activity")
            ->where("ts.id=:idTs")
            ->setParameter("idTs", $idTimeSlot)
            //->setParameter("idTs", $idTimeSlot)
            ->getQuery()->getArrayResult();
    }

    public function getAvailablePrices($groupsId, $idTimeSlot, $qty)
    {
        $qb = $this->createQueryBuilder("p");
        return $qb->select('p', 'tp', $qb->expr()->min('tp.qty'))
            ->join('p.groups', 'g')
            ->innerJoin("ZenwebAventureParcBundle:TimeSlot", "ts", "WITH", "ts.activity = p.activity")
            ->join('p.TierPrices', 'tp')
            ->where($qb->expr()->in('g.id', $groupsId))
            ->andWhere("ts.id=:idTs")
            ->andWhere("tp.qty>=:qtyWanted")
            ->setParameter("idTs", $idTimeSlot)
            ->setParameter("qtyWanted", $qty)
            ->getQuery()->getArrayResult();
    }
}
