<?php

namespace Zenweb\Aventure\ParcBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SalesFlatOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesFlatOrderRepository extends EntityRepository
{
    public function getPlacesReserved($date, $tsId) {
        $qb = $this->createQueryBuilder("sfo");
        return $qb->select('SUM(sfi.qty) as places')
            ->join("ZenwebAventureParcBundle:SalesFlatItem", "sfi", "WITH", "sfo.id = sfi.order")
            ->where('sfo.bookingDate = :bookedDate')
            ->andWhere('sfi.timeSlot = :tsId')
            ->groupBy('sfi.timeSlot')
            ->setParameter("bookedDate", $date)
            ->setParameter("tsId", $tsId)
            ->getQuery()->getOneOrNullResult();

    }
}
