<?php

namespace Zenweb\Aventure\ParcBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TierPriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TierPriceRepository extends EntityRepository
{
}
