Zenweb\Aventure\ParcBundle\Entity\Extra:
    type: entity
    table: null
    repositoryClass: Zenweb\Aventure\ParcBundle\Entity\ExtraRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
        pricePerUnit:
            type: decimal
            column: price_per_unit
        qtyMin:
            type: integer
            column: qty_min
        enabled:
            type: boolean
        status:
            type: boolean

    manyToMany:
        parcs:
            targetEntity: Parc
            joinTable:
                name: extras_parcs
                joinColumns:
                    extra_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    parc_id:
                        referencedColumnName: id
        typicalDays:
            targetEntity: TypicalDay
            joinTable:
                name: extras_typical_days
                joinColumns:
                    extra_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    typicalDay_id:
                        referencedColumnName: id

    lifecycleCallbacks: {  }
