Zenweb\Aventure\ParcBundle\Entity\Group:
    type:  entity
    table: fos_user_group
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    lifecycleCallbacks: {  }
