Zenweb\Aventure\ParcBundle\Entity\Price:
    type: entity
    table: price
    repositoryClass: Zenweb\Aventure\ParcBundle\Entity\PriceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
        price:
            type: decimal
        enabled:
            type: boolean

    oneToMany:
        TierPrices:
            targetEntity: TierPrice
            mappedBy: activity_price
    manyToOne:
        activity:
            targetEntity: Zenweb\Aventure\ParcBundle\Entity\Activity
            inversedBy: Prices
    manyToMany:
        groups:
            targetEntity: Group
            joinTable:
                name: prices_groups
                joinColumns:
                    price_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
