Zenweb\Aventure\ParcBundle\Entity\SalesFlatOrder:
    type: entity
    table: sales_flat_order
    repositoryClass: Zenweb\Aventure\ParcBundle\Entity\SalesFlatOrderRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        reference:
            type: string
            length: 255
            nullable: true
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
        state:
            type: string
            length: '32'
            nullable: true
        status:
            type: string
            length: '32'
            nullable: true
        baseTotal:
            type: decimal
            column: base_total
            nullable: true
        baseTotalPaid:
            type: decimal
            column: base_total_paid
            nullable: true
        bookingDate:
            type: date
            column: booking_date
        checkoutMethod:
            type: string
            length: 255
            column: checkout_method
            nullable: true
        comment:
            type: text
            nullable: true
        couponCode:
            type: string
            length: 255
            column: coupon_code
            nullable: true
    oneToMany:
        items:
            targetEntity: SalesFlatItem
            mappedBy: order
            cascade: ["persist", "remove"]
            orphanRemoval: true
    manyToOne:
        user:
            targetEntity: User
            inversedBy: orders
        #parc:
        #    targetEntity: Parc
        #    inversedBy: flat_order
        #    joinColumn:
        #        name: parc_id
        #        referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [updatedTimestamps, calculateTotal]
        preUpdate: [updatedTimestamps, calculateTotal]
