Zenweb\Aventure\ParcBundle\Entity\SalesFlatExtra:
    type: entity
    table: sales_flat_extra
    repositoryClass: Zenweb\Aventure\ParcBundle\Entity\SalesFlatExtraRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
        name:
            type: string
            length: 255
            nullable: true
        description:
            type: text
            nullable: true
        qty:
            type: integer
            nullable: true
        rowTotal:
            type: decimal
            column: row_total
            nullable: true
    manyToOne:
        order:
            targetEntity: Zenweb\Aventure\ParcBundle\Entity\SalesFlatOrder
            inversedBy: extras
    lifecycleCallbacks:
         prePersist: [updatedTimestamps]
         preUpdate: [updatedTimestamps]
