Zenweb\Aventure\ParcBundle\Entity\User:
    type:  entity
    table: fos_user_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        mobile:
            type: string
            length: 64
            nullable: true
        address:
            type: text
            nullable: true
        commentary:
            type: text
            nullable: true
        newsletter:
            type: boolean

    oneToOne:
        flat_order:
            targetEntity: SalesFlatOrder
            mappedBy: user

    lifecycleCallbacks: {  }
