<?php

namespace Zenweb\Accro\ParcBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExtraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtraRepository extends EntityRepository
{
}
