<?php

namespace Zenweb\Accro\ParcBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypicalDayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypicalDayRepository extends EntityRepository
{
}
