parameters:
#    zenweb_accro_parc.example.class: Zenweb\Accro\ParcBundle\Example

services:
#    zenweb_accro_parc.example:
#        class: %zenweb_accro_parc.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
