zenweb_aventure_parc_payment_success:
    pattern: /payment/success
    defaults: { _controller: ZenwebAventureParcPaymentBundle:Payment:paymentSuccess }

zenweb_aventure_parc_payment_error:
    pattern: /payment/error
    defaults: { _controller: ZenwebAventureParcPaymentBundle:Payment:paymentError }

zenweb_aventure_parc_payment:
    pattern: /payment/{order}
    defaults: { _controller: ZenwebAventureParcPaymentBundle:Payment:payment, order: null }

