Zenweb\Accro\ParcBundle\Entity\TimeSlot:
    type: entity
    table: null
    repositoryClass: Zenweb\Accro\ParcBundle\Entity\TimeSlotRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        beginTime:
            type: time
            column: begin_time
        endTime:
            type: time
            column: end_time
        capacity:
            type: integer
    manyToOne:
        typicalDay:
            targetEntity: Zenweb\Accro\ParcBundle\Entity\TypicalDay
            inversedBy: TimeSlots
        activity:
            targetEntity: Zenweb\Accro\ParcBundle\Entity\Activity
    lifecycleCallbacks: {  }
