Zenweb\Accro\ParcBundle\Entity\TypicalDay:
    type: entity
    table: null
    repositoryClass: Zenweb\Accro\ParcBundle\Entity\TypicalDayRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
        beginTime:
            type: time
            column: begin_time
        endTime:
            type: time
            column: end_time
        frequency:
            type: integer
        color:
            type: string
            length: 25
    lifecycleCallbacks: {  }
